name: Deploy Static HTML Site

on:
  push:
    branches:
      - main  # Triggers deployment whenever you push changes to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Files
        uses: actions/checkout@v4

      - name: Set Up SSH Key Configuration
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.MYSERVER }}

          known_hosts: 'placeholder'
          if_key_exists: replace

      - name: Trust Server Public Fingerprint
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Push Files to Lightsail via Rsync
        run: |
          rsync -avz --delete \
            --exclude '.git*' \
            --exclude '.github*' \
            ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/html/

      - name: Fix Directory Ownership Rules
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "sudo chown -R www:www /www/wwwroot/awstest.work.gd"
